spring:
  config:
    activate:
      on-profile: dev-local
  datasource:
    url: jdbc:mysql://localhost:3306/endpoint-monitor_db?characterEncoding=utf8
    username: endpoint-monitor-admin
    password: endpoint-password
  jpa:
    hibernate:
      ddl-auto: create-drop                                    # When liquibase migrations enabled - change to 'none'
    defer-datasource-initialization: true                      # Necessary for db scheme making before the init security data is inserted
  sql:
    init:
      mode: always
      data-locations: classpath:/db/init/00_sec_users.sql